[build]
  # Comando para build do projeto (apenas frontend)
  command = "npm run build:client"
  
  # Diretório onde os arquivos buildados serão colocados
  publish = "dist/public"

# Configurações para Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para otimização
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de Node.js para o build
[build.environment]
  NODE_VERSION = "18" 